### ISSUE TITLE
support Yarn

### ISSUE THREAD

**Issue by chrisbraddock** [GeekAb/switch-registry#9]
After running `npmrs use <private repo name>` ... `yarn config list` still shows Yarn pointing at **https://registry.npmjs.org/**.

**Comment by GeekAb** [comment]
Will look into it. Never tested it with yarn though. 

Opening it for others also if anyone want to look into it.

**Comment by GeekAb** [comment]
@chrisbraddock what's the current npmrs version you are using?

**Comment by chrisbraddock** [comment]
@GeekAb 1.1.7

**Comment by GeekAb** [comment]
@chrisbraddock I tried it with yarn but couldn't reproduce.

Can you please share output of `npm list --depth 1 --global switch-registry`

Or if you can share any more details it will be helpful.

**Comment by IdkMan2** [comment]
Any progress on this issue?

**Comment by GeekAb** [comment]
@IdkMan2 I have a separate script to manage yarn registries. Let me merge both and see if it works fine :)

**Comment by GeekAb** [comment]
Made an update with yarn support
